### ISSUE TITLE
HB_Logic Break Heart Beat 

### ISSUE THREAD

**Issue by Von-dy** [Von-dy/Game_Design_Final_Project#14]
Something about HB_Logic breaks the way the heart beat tracker method works. The function tested in isolation has no bugs and when hb_logic is commented out everything works fine.

**Comment by Shasties** [comment]
Fixed by changing global variable name to z for use in heartbeat(). 

Unsure where global x is being called by hb_logic. Possible deletion of local x->calling global x?
